# Generated by Django 5.1.6 on 2025-02-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('connections', models.JSONField()),
            ],
            options={
                'db_table': 'gate',
            },
        ),
    ]
