name: Deploy Terraform

on:
  push:
    branches:
      - createApp

jobs:
  terraform:
    name: Apply Terraform Configuration
    runs-on: self-hosted

    env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2


      - name: Initialize Terraform
        run: |
              terraform init
        working-directory: terraform

      - name: Kill Stuck Terraform Processes
        run: pkill -f terraform || true

      - name: Validate Terraform
        run: |
              echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
              echo "AWS_REGION: ${{ secrets.AWS_REGION }}"
              terraform validate
        working-directory: terraform
        

      - name: Check AWS Credentials
        run: aws sts get-caller-identity


      - name: Plan Terraform
        run: |
              echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
              echo "AWS_REGION: ${{ secrets.AWS_REGION }}"
              export TF_LOG=DEBUG
              export TF_LOG_PATH=terraform-debug.log
              terraform plan
        working-directory: terraform

      - name: Apply Terraform Configuration
        run: terraform apply -auto-approve
        working-directory: terraform
