name: Deploy ECS and RDS instances

on:
  push:
    branches:
      - createApp

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Homebrew
      run: |
        if ! command -v brew &> /dev/null; then
          echo "Homebrew not found, installing..."
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" < /dev/null
          echo "export PATH=/opt/homebrew/bin:$PATH" >> $GITHUB_ENV  # Ensure Homebrew is in PATH
        else
          echo "Homebrew already installed"
        fi

    - name: Install PostgreSQL client using Homebrew
      run: |
        brew install postgresql

    - name: Set up environment variables
      run: |
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
        echo "DB_USERNAME=${{ secrets.DB_USER }}" >> $GITHUB_ENV

    - name: Initialise terraform
      run: terraform init
      working-directory: terraform

    - name: Validate terraform
      run: terraform validate
      working-directory: terraform

    - name: Apply terraform
      run: |
        terraform apply -auto-approve \
        -var "db_username=$DB_USERNAME" \
        -var "db_password=$DB_PASSWORD"
      working-directory: terraform


    - name: Set up environment variables
      run: |
        echo "DB_HOST=$(terraform output -raw rds_host)" >> $GITHUB_ENV
        echo "DB_PORT=$(terraform output -raw rds_port)" >> $GITHUB_ENV

    - name: Run SQL script on RDS
      run: |
        PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -p $DB_PORT -U $DB_USERNAME -d mydb -f create-local-postgres-db.sql
        working-directory: sql